# Cloudflare Pages Configuration
# This file configures the Cloudflare Pages deployment settings

[settings]
# Project name (must match your Cloudflare Pages project)
name = "createx-facilitator-guide"

# Build configuration
[build]
command = "npm run build"
destination = "out"

# Environment variables for build
[build.environment]
NODE_VERSION = "18"
NPM_VERSION = "9"

# Custom headers for security and performance
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "SAMEORIGIN"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Cache static assets
[[headers]]
for = "/_next/static/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
for = "*.{png,jpg,jpeg,gif,webp,svg,ico}"
[headers.values]
Cache-Control = "public, max-age=86400"

# Redirects for internationalization
[[redirects]]
from = "/"
to = "/en"
status = 302
force = false
