name = "createx-facilitator-guide"
main = "workers/api/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Database Configuration
[[d1_databases]]
binding = "DB"
database_name = "createx-cms"
database_id = "placeholder-database-id"

# KV Storage for Caching
[[kv_namespaces]]
binding = "CACHE_KV"
id = "placeholder-kv-id"
preview_id = "placeholder-preview-kv-id"

# R2 Bucket for Asset Storage
[[r2_buckets]]
binding = "ASSETS"
bucket_name = "createx-assets"

# R2 Bucket for Content Storage
[[r2_buckets]]
binding = "CONTENT_BUCKET"
bucket_name = "createx-content"

# AI Binding for Content Generation
[ai]
binding = "AI"

# Analytics Engine for Tracking
[[analytics_engine_datasets]]
binding = "ANALYTICS"

# Durable Objects for Real-time Features
[[durable_objects.bindings]]
name = "COLLABORATION_SESSION"
class_name = "CollaborationSession"

[[durable_objects.bindings]]
name = "LIVE_SESSIONS"
class_name = "LiveSession"

[[migrations]]
tag = "v1"
new_classes = ["CollaborationSession", "LiveSession"]

# Environment Variables
[vars]
ENVIRONMENT = "development"
APP_URL = "https://createx-facilitator-guide.pages.dev"
CORS_ORIGINS = "https://createx-facilitator-guide.pages.dev"
JWT_SECRET = "b7e2f8c6a1d94e3b9c2f4d5e6a7b8c9d"
ENCRYPTION_KEY = "e3f1c2d4b5a6e7f8c9b0a1d2e3f4b5c6"
API_VERSION = "v1"
OPENAI_API_KEY = "your-openai-key"

# Production Environment
[env.production.vars]
ENVIRONMENT = "production"
APP_URL = "https://facilitator.createx.org"
CORS_ORIGINS = "https://facilitator.createx.org"
JWT_SECRET = "production-jwt-secret"
ENCRYPTION_KEY = "production-encryption-key"
API_VERSION = "v1"
OPENAI_API_KEY = "production-openai-key"

[env.production.d1_databases]
database_name = "createx-cms-prod"
database_id = "production-database-id"

[env.production.kv_namespaces]
id = "production-kv-id"
preview_id = "production-preview-kv-id"

# Staging Environment
[env.staging.vars]
ENVIRONMENT = "staging"
APP_URL = "https://staging-facilitator.createx.org"
CORS_ORIGINS = "https://staging-facilitator.createx.org"
